### PR TITLE
PR for Deliverable 1 because first one was rejected due to formatting

### PR DESCRIPTION
**Pull request by APXBUCS**
We will add Aidan as a reviewer, once we figure out his GitHub username.

### CODE REVIEW

**Comment by APXBUCS** [comment]
Aidan has been added as a reviewer now

**Comment by aimgo** [comment]
Could you fix the readme conflicts

**Comment by APXBUCS** [comment]
Readme conflict fixed

**Review by aimgo — APPROVED** [review]
👍

**Pull request merged**
